apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir:
      medium: Memory

# medium: Memory, means use memory not disk;
# emptyDir created as Pod create, and Deleted as pod destroy;
# Default Directory: var/lib/kubelet/pods/49e7a02c-0f1f-11e7-888f-42010a8a0004/volumes/kubernetes.io~empty-dir

