apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: test
      image: busybox
      volumeMounts:
        - name: config-vol
          mountPath: /etc/config
  volumes:
    - name: config-vol
      configMap:
        name: log-config
        items:
          - key: log_level
            path: log_level


# volume will map the ConfigMap: log-config
# volume of log_level(ConfigMap:log-config) will save to /etc/config/log_level file in the Pod
